// mutable memory for the game

import { unitStats } from "./unitStats.js";

//
export const Phase = {
  MENU: "menu",
  DIALOGUE: "dialogue",
  PLAYER_SELECT: "player_select",
  PLAYER_ACTION: "player_action",
  PLAYER_ATTACK: "player_attack",
  PLAYER_MOVE: "player_move",
  PLAYER_SKILL: "player_skill",
  PLAYER_ITEM: "player_item",
  ENEMY_TURN: "enemy_turn",
  GAME_OVER: "game_over",
};

export function createInitialUnits() {
  return [
    // All Around Strong
    // new unitStats({
    //   playerId: 0,
    //   name: "Johnny",
    //   unitType: "Knight",
    //   variant: "knight_1",
    //   affiliation: 0,
    //   row: 3,
    //   col: 9,
    //   maxHealth: 50,
    //   health: 50,
    //   strength: 20,
    //   intelligence: 10,
    //   skill: 15,
    //   speed: 15,
    //   luck: 15,
    //   defense: 7,
    //   resistance: 7,
    //   movement: 3,
    //   equipped: null,
    //   inventory: [{ id: "heroSword" }, { id: "potion" }, { id: "potion" }],
    //   skills: [{ id: "empoweredStrike", uses: 3 }],
    //   // intelligence: 10,
    // }),
    // // Glass Cannon
    // new unitStats({
    //   playerId: 1,
    //   name: "Abram",
    //   unitType: "Wizard",
    //   variant: "wizard_1",
    //   affiliation: 0,
    //   row: 2,
    //   col: 8,
    //   maxHealth: 20,
    //   health: 20,
    //   // strength: 20,
    //   intelligence: 25,
    //   skill: 20,
    //   speed: 10,
    //   luck: 15,
    //   defense: 7,
    //   resistance: 7,
    //   movement: 2,
    //   range: 2,
    //   inventory: [{ id: "potion" }],
    //   skills: [{ id: "fireball", uses: 2 }],
    // }),
    // // Mina Build
    // new unitStats({
    //   playerId: 2,
    //   name: "Esmy",
    //   unitType: "Knight",
    //   variant: "knight_1",
    //   affiliation: 0,
    //   row: 3,
    //   col: 7,
    //   maxHealth: 30,
    //   health: 30,
    //   strength: 13,
    //   // intelligence: 10,
    //   skill: 25,
    //   speed: 15,
    //   luck: 25,
    //   defense: 5,
    //   resistance: 15,
    //   movement: 5,
    //   inventory: [{ id: "runeRapier" }, { id: "potion" }],
    //   skills: [{ id: "empoweredStrike", uses: 3 }],
    // }),
    // // Health Tank
    // new unitStats({
    //   playerId: 3,
    //   name: "Tyler",
    //   unitType: "Knight",
    //   variant: "knight_2",
    //   affiliation: 1,
    //   row: 7,
    //   col: 8,
    //   maxHealth: 99,
    //   health: 99,
    //   strength: 18,
    //   // intelligence: 10,
    //   skill: 20,
    //   speed: 15,
    //   luck: 20,
    //   defense: 10,
    //   resistance: 10,
    //   movement: 2,
    //   // equipped: "bronzeSword",
    //   inventory: [],
    //   skills: [],
    // }),
    // // High Def
    // new unitStats({
    //   playerId: 4,
    //   name: "Emi",
    //   unitType: "Knight",
    //   variant: "knight_2",
    //   affiliation: 1,
    //   row: 8,
    //   col: 7,
    //   maxHealth: 20,
    //   health: 20,
    //   strength: 20,
    //   // intelligence: 10,
    //   skill: 15,
    //   speed: 15,
    //   luck: 15,
    //   defense: 35,
    //   resistance: 20,
    //   movement: 2,
    //   inventory: [],
    //   skills: [],
    // }),
    // // High Res
    // new unitStats({
    //   playerId: 5,
    //   name: "David",
    //   unitType: "Knight",
    //   variant: "knight_2",
    //   affiliation: 1,
    //   row: 8,
    //   col: 9,
    //   maxHealth: 30,
    //   health: 30,
    //   strength: 23,
    //   // intelligence: 10,
    //   skill: 15,
    //   speed: 15,
    //   luck: 15,
    //   defense: 20,
    //   resistance: 35,
    //   movement: 2,
    //   inventory: [],
    //   skills: [],
    // }),
    // // Evasion Wizard
    // new unitStats({
    //   playerId: 5,
    //   name: "Joseph",
    //   unitType: "Wizard",
    //   variant: "wizard_2",
    //   affiliation: 1,
    //   row: 9,
    //   col: 8,
    //   maxHealth: 10,
    //   health: 10,
    //   // strength: 15,
    //   intelligence: 30,
    //   skill: 15,
    //   speed: 15,
    //   luck: 60,
    //   defense: 5,
    //   resistance: 5,
    //   movement: 4,
    //   inventory: [],
    //   skills: [],
    // }),

    new unitStats({
      playerId: 0,
      name: "Friendly 1",
      unitType: "Knight",
      variant: "knight_1",
      affiliation: 0,
      row: 7,
      col: 10,
      maxHealth: 10,
      health: 5,
      strength: 15,
      // intelligence: 30,
      skill: 15,
      speed: 15,
      luck: 15,
      defense: 5,
      resistance: 5,
      movement: 4,
      inventory: [],
      skills: [],
    }),
    new unitStats({
      playerId: 1,
      name: "Friendly 2",
      unitType: "Knight",
      variant: "knight_1",
      affiliation: 0,
      row: 7,
      col: 11,
      maxHealth: 10,
      health: 1,
      strength: 15,
      // intelligence: 30,
      skill: 15,
      speed: 15,
      luck: 15,
      defense: 5,
      resistance: 5,
      movement: 4,
      inventory: [],
      skills: [],
    }),

    new unitStats({
      playerId: 2,
      name: "Enemy 1",
      unitType: "Knight",
      variant: "knight_2",
      affiliation: 1,
      row: 10,
      col: 10,
      maxHealth: 10,
      health: 10,
      strength: 1,
      // intelligence: 30,
      skill: 15,
      speed: 15,
      luck: 15,
      defense: 5,
      resistance: 5,
      movement: 6,
      inventory: [],
      skills: [],
    }),

    new unitStats({
      playerId: 3,
      name: "Enemy 2",
      unitType: "Knight",
      variant: "knight_2",
      affiliation: 1,
      row: 9,
      col: 10,
      maxHealth: 10,
      health: 10,
      strength: 0,
      // intelligence: 30,
      skill: 15,
      speed: 15,
      luck: 15,
      defense: 5,
      resistance: 5,
      movement: 6,
      inventory: [],
      skills: [],
    }),

    new unitStats({
      playerId: 1,
      name: "Friendly 3",
      unitType: "Knight",
      variant: "knight_1",
      affiliation: 0,
      row: 7,
      col: 9,
      maxHealth: 10,
      health: 10,
      strength: 15,
      // intelligence: 30,
      skill: 15,
      speed: 15,
      luck: 15,
      defense: 5,
      resistance: 5,
      movement: 4,
      inventory: [],
      skills: [],
    }),
  ];
}

export function createInitialState() {
  return {
    currentMenu: "startCover",
    enemyMoves: [],
    closestFriendly: null,
    optimalMove: null,

    i: 0,
    units: createInitialUnits(),

    gameStart: false,
    phase: Phase.MENU,
    turnCounter: 1,
    playerTurn: true,

    board: { rows: 12, cols: 12 },
    hover: { row: 0, col: 0 },
    attackHover: { row: 0, col: 0 },

    selectedUnit: null,
    playerSelected: false,
    useSkill: null,

    isTargeting: false,
    unitHighlighted: false,
    receivingUnit: null,
    attackOn: false,
    startRow: 0,
    startCol: 0,

    playerWon: false,

    currentUnitsQueue: [],

    mapObstacles: [
      [1, 0],
      [2, 0],
      // [7, 0],
      // [8, 0],
      // [9, 0],
      // [10, 0],
      // [11, 0],
      // [8, 1],
      // [9, 1],
      // [10, 1],
      // [11, 1],
      // [9, 2],
      // [10, 2],
      // [11, 2],
      // [11, 3],
      [4, 4],
      [5, 4],
      [6, 4],
      [4, 5],
      [5, 5],
      // [6, 5],
      [4, 6],
      [5, 6],
      [6, 6],
      [1, 9],
      [2, 9],
      [1, 10],
      [2, 10],
    ],

    obstacleTypes: {
      rock: [
        [1, 0],
        [2, 0],
        [1, 9],
        [2, 9],
        [1, 10],
        [2, 10],
      ],
      castle: [
        [4, 4],
        [5, 4],
        [6, 4],
        [4, 5],
        [5, 5],
        // [6, 5],
        [4, 6],
        [5, 6],
        [6, 6],
      ],
      forest: [
        [7, 0],
        [8, 0],
        [9, 0],
        [10, 0],
        [11, 0],
        [8, 1],
        [9, 1],
        [10, 1],
        [11, 1],
        [9, 2],
        [10, 2],
        [11, 2],
        [11, 3],
      ],
      castleGate: [[6, 5]],
    },

    obstacles: [],

    highTile: [],

    attackTile: [],
  };
}
