// mutable memory for the game

import { unitStats } from "./unitStats.js";

//
export const Phase = {
  MENU: "menu",
  DIALOGUE: "dialogue",
  PLAYER_SELECT: "player_select",
  PLAYER_ACTION: "player_action",
  PLAYER_ATTACK: "player_attack",
  PLAYER_SKILL: "player_skill",
  PLAYER_ITEM: "player_item",
  ENEMY_TURN: "enemy_turn",
  GAME_OVER: "game_over",
};

export function createInitialUnits() {
  return [
    new unitStats({
      playerId: 0,
      name: "Johnny",
      unitType: "knight",
      variant: "knight_1",
      affiliation: 0,
      row: 2,
      col: 7,
      strength: 10,
      movement: 3,
      maxHealth: 35,
      health: 35,
      skill: 50,
      equipped: null,
      inventory: [{ id: "potion" }, { id: "potion" }, { id: "ironSword" }],
      skills: [{ id: "empoweredStrike", uses: 3 }],
      // intelligence: 10,
    }),
    new unitStats({
      playerId: 1,
      name: "Abram",
      unitType: "wizard",
      variant: "wizard_1",
      affiliation: 0,
      maxHealth: 20,
      health: 20,
      row: 1,
      col: 6,
      strength: 4,
      inventory: [{ id: "potion" }],
      skills: [{ id: "fireball", uses: 2 }],
      movement: 2,
      range: 2,
      intelligence: 15,
    }),
    new unitStats({
      playerId: 2,
      name: "Esmy",
      unitType: "knight",
      variant: "knight_1",
      affiliation: 0,
      row: 2,
      col: 5,
      movement: 4,
      strength: 6,
      maxHealth: 45,
      health: 45,
      inventory: [{ id: "potion" }],
      skills: [{ id: "empoweredStrike", uses: 3 }],
    }),
    new unitStats({
      playerId: 3,
      name: "Tyler",
      unitType: "knight",
      variant: "knight_2",
      affiliation: 1,
      row: 7,
      col: 3,
      movement: 5,
      strength: 5,
      inventory: [],
      skills: [],
      maxHealth: 30,
      health: 30,
    }),
    new unitStats({
      playerId: 4,
      name: "Emi",
      unitType: "knight",
      variant: "knight_2",
      affiliation: 1,
      row: 8,
      col: 7,
      movement: 2,
      strength: 6,
      maxHealth: 25,
      health: 25,
      inventory: [],
      skills: [],
    }),
    new unitStats({
      playerId: 5,
      name: "David",
      unitType: "knight",
      variant: "knight_2",
      affiliation: 1,
      row: 8,
      col: 9,
      movement: 1,
      strength: 10,
      inventory: [],
      skills: [],
      maxHealth: 55,
      health: 55,
    }),

    new unitStats({
      playerId: 6,
      name: "Joseph",
      unitType: "wizard",
      variant: "wizard_2",
      affiliation: 1,
      row: 8,
      col: 2,
      movement: 4,
      strength: 4,
      inventory: [],
      skills: [],
      maxHealth: 15,
      health: 15,
    }),
    new unitStats({
      playerId: 7,
      name: "Seabass",
      unitType: "wizard",
      variant: "wizard_2",
      affiliation: 1,
      row: 9,
      col: 8,
      movement: 4,
      strength: 4,
      inventory: [],
      skills: [],
      maxHealth: 20,
      health: 20,
    }),
    new unitStats({
      playerId: 8,
      name: "Ivana",
      unitType: "knight",
      variant: "knight_2",
      affiliation: 1,
      row: 7,
      col: 1,
      movement: 5,
      strength: 5,
      health: 30,
      maxHealth: 30,
      inventory: [],
      skills: [],
    }),
    new unitStats({
      playerId: 9,
      name: "Mike",
      unitType: "wizard",
      variant: "wizard_2",
      affiliation: 1,
      row: 8,
      col: 5,
      movement: 5,
      strength: 5,
      health: 20,
      maxHealth: 20,
      inventory: [],
      skills: [],
    }),
  ];
}

export function createInitialState() {
  return {
    currentMenu: "startCover",
    enemyMoves: [],
    closestFriendly: null,
    optimalMove: null,

    i: 0,
    units: createInitialUnits(),

    gameStart: false,
    phase: Phase.MENU,
    turnCounter: 1,
    playerTurn: true,

    board: { rows: 12, cols: 12 },
    hover: { row: 0, col: 0 },
    attackHover: { row: 0, col: 0 },

    selectedUnit: null,
    playerSelected: false,
    useSkill: null,

    isTargeting: false,
    unitHighlighted: false,
    receivingUnit: null,
    attackOn: false,
    startRow: 0,
    startCol: 0,

    currentUnitsQueue: [],

    mapObstacles: [
      [1, 0],
      [2, 0],
      // [7, 0],
      // [8, 0],
      // [9, 0],
      // [10, 0],
      // [11, 0],
      // [8, 1],
      // [9, 1],
      // [10, 1],
      // [11, 1],
      // [9, 2],
      // [10, 2],
      // [11, 2],
      // [11, 3],
      [4, 4],
      [5, 4],
      [6, 4],
      [4, 5],
      [5, 5],
      // [6, 5],
      [4, 6],
      [5, 6],
      [6, 6],
      [1, 9],
      [2, 9],
      [1, 10],
      [2, 10],
    ],

    obstacleTypes: {
      rock: [
        [1, 0],
        [2, 0],
        [1, 9],
        [2, 9],
        [1, 10],
        [2, 10],
      ],
      castle: [
        [4, 4],
        [5, 4],
        [6, 4],
        [4, 5],
        [5, 5],
        // [6, 5],
        [4, 6],
        [5, 6],
        [6, 6],
      ],
      forest: [
        [7, 0],
        [8, 0],
        [9, 0],
        [10, 0],
        [11, 0],
        [8, 1],
        [9, 1],
        [10, 1],
        [11, 1],
        [9, 2],
        [10, 2],
        [11, 2],
        [11, 3],
      ],
      castleGate: [[6, 6]],
    },

    obstacles: [],

    highTile: [],

    attackTile: [],
  };
}
